import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
import React from '../web/node_modules/react/index.js';import {renderToStaticMarkup} from '../web/node_modules/react-dom/server.node.js';import Markdown from '../web/node_modules/react-markdown/index.js';import gfm from '../web/node_modules/remark-gfm/index.js';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),source=path.join(root,'landing'),out=path.join(root,'web/public/about'),repo='https://github.com/nadeemmhdm/Nila-Personal-Assistant';
fs.mkdirSync(out,{recursive:true});const version=JSON.parse(fs.readFileSync(path.join(root,'web/package.json'))).version;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const docs=[['google','docs/GOOGLE_CONNECT.md','Google connections','Deploy the PHP OAuth broker and connect read-only services'],['readme','README.md','Setup & commands','Installation, models and everyday use'],['troubleshooting','docs/TROUBLESHOOTING.md','Troubleshooting','Error codes and recovery steps'],['learning','docs/LEARNING_LAB.md','Learning Lab','How topic reviews and saved lessons work'],['security','SECURITY.md','Security & privacy','Data boundaries and reporting issues'],['contributing','CONTRIBUTING.md','Contribute','Build, test and improve Nila'],['license','LICENSE','MIT license','Permissions, terms and warranty']];
function markdown(text,file='README.md'){return renderToStaticMarkup(React.createElement(Markdown,{remarkPlugins:[gfm],skipHtml:true,urlTransform:url=>{if(/^https?:\/\//.test(url)||url.startsWith('#'))return url;const normalized=path.posix.normalize(path.posix.join(path.posix.dirname(file),url));const match=docs.find(d=>d[1]===normalized);return match?'guide-'+match[0]+'.html':repo+'/blob/main/'+normalized;},children:text}))}
for(const [id,file,title] of docs){const raw=fs.readFileSync(path.join(root,file),'utf8');const content=id==='license'?'<h1>MIT License</h1><pre>'+escape(raw)+'</pre>':markdown(raw,file);fs.writeFileSync(path.join(out,'guide-'+id+'.html'),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · Nila</title><link rel="icon" href="nila-logo.png"><link rel="stylesheet" href="style.css"></head><body><header><a class="brand" href="index.html"><img src="nila-logo.png" alt="">nila<span>.</span></a><a href="index.html#docs">← All documentation</a></header><main class="doc-body">${content}</main><footer class="wrap">Nila ${version} · <a href="${repo}/blob/main/${file}">View source</a></footer></body></html>`)}
const errors=JSON.parse(fs.readFileSync(path.join(source,'errors.json'),'utf8'));
let releases=JSON.parse(fs.readFileSync(path.join(source,'releases.json'),'utf8'));
for(const file of fs.readdirSync(path.join(root,'docs/releases')).filter(x=>/^v[\d.]+\.md$/.test(x))){const tag=file.slice(0,-3),body=fs.readFileSync(path.join(root,'docs/releases',file),'utf8');const existing=releases.find(x=>x.tag===tag);if(existing)existing.body=body;else releases.push({tag,name:body.split('\n')[0].replace(/^# /,''),body,url:repo+'/releases/tag/'+tag})}
releases.sort((a,b)=>b.tag.localeCompare(a.tag,undefined,{numeric:true}));
const errorHTML=errors.map(e=>`<article class="error-card"><code>${escape(e.code)}</code><h3>${escape(e.title)}</h3><p>${escape(e.help)}</p></article>`).join('');
const releaseHTML=releases.map(x=>`<details><summary>${escape(x.name)}</summary><div class="release-body">${markdown(x.body)}<a href="${escape(x.url)}">Release on GitHub ↗</a></div></details>`).join('');
const docsHTML=docs.map(([id,file,title,description])=>`<a class="doc-link" href="guide-${id}.html"><strong>${title} ↗</strong><span>${description}</span></a>`).join('');
let html=fs.readFileSync(path.join(source,'index.html'),'utf8').replaceAll('@@VERSION@@',version).replace('@@ERRORS@@',errorHTML).replace('@@RELEASES@@',releaseHTML).replace('@@DOCS@@',docsHTML);fs.writeFileSync(path.join(out,'index.html'),html);
for(const file of ['style.css','app.js'])fs.copyFileSync(path.join(source,file),path.join(out,file));fs.copyFileSync(path.join(root,'web/public/nila-logo.png'),path.join(out,'nila-logo.png'));
fs.writeFileSync(path.join(out,'.nojekyll'),'');console.log(`Built Nila ${version} landing page, ${docs.length} guides, ${releases.length} releases, ${errors.length} help entries`);
