import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Check,ChevronDown} from 'lucide-react';
type Choice={value:string;label:string;detail?:string;icon?:ReactNode};
export function ChoiceMenu({label,value,options,icon,compact=false,disabled=false,onChange}:{label:string;value:string;options:Choice[];icon:ReactNode;compact?:boolean;disabled?:boolean;onChange:(value:string)=>void}){
 const [open,setOpen]=useState(false),root=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null);
 const selected=options.find(o=>o.value===value);
 useEffect(()=>{if(!open)return;function outside(e:PointerEvent){if(!root.current?.contains(e.target as Node))setOpen(false)}function escape(e:KeyboardEvent){if(e.key==='Escape'){setOpen(false);trigger.current?.focus()}}document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape)}},[open]);
 useEffect(()=>{if(disabled)setOpen(false)},[disabled]);
 return <div className="choice" ref={root}><button type="button" ref={trigger} className={'choice-trigger '+(compact?'icon':'')} title={`${label}: ${selected?.label||value}`} aria-label={label} aria-haspopup="listbox" aria-expanded={open} disabled={disabled} onClick={()=>setOpen(!open)}>{icon}{!compact&&<span>{selected?.label||'Choose model'}</span>}<ChevronDown size={11}/></button>{open&&<div className="choice-menu" role="listbox" aria-label={label} onKeyDown={e=>{const all=Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>('[role=option]'));const index=all.indexOf(document.activeElement as HTMLButtonElement);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();all[(index+(e.key==='ArrowDown'?1:-1)+all.length)%all.length]?.focus()}}}><div className="choice-heading">{label}</div>{options.map(o=><button type="button" key={o.value} role="option" aria-selected={value===o.value} onClick={()=>{setOpen(false);onChange(o.value);trigger.current?.focus()}}>{o.icon}<span><strong>{o.label}</strong>{o.detail&&<small>{o.detail}</small>}</span>{value===o.value&&<Check size={16}/>}</button>)}</div>}</div>
}
