import {ProfileCards} from './ModelSelector';
import {useEffect,useRef,useState} from 'react';
import {workApi} from './Workspace';
export function Models(){
 const [data,setData]=useState<any>(null),[name,setName]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function refresh(){try{setData(await workApi('/system'))}catch(e:any){setNotice(e.message)}}
 useEffect(()=>{refresh();const t=setInterval(refresh,4000);return()=>clearInterval(t)},[]);
 async function action(path:string,model:string){setBusy(true);setNotice(path==='load'?'Loading into local memory…':'Starting download…');try{await workApi('/models/'+path,'POST',{model});await refresh();window.dispatchEvent(new Event('nila-settings-changed'));setNotice(path==='load'?'Model loaded and selected for new answers.':'Download started. Progress appears below.')}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 return <section><h2>Ollama models</h2><p>Choose Fast, Medium or Smart, or keep using any installed Ollama model.</p><ProfileCards installed={data?.models||[]} busy={busy} load={name=>action("load",name)} download={name=>action("pull",name)}/><p role="status">{notice}</p><button disabled={busy} onClick={refresh}>Refresh models</button><p>{data?.models?.length||0} installed · Active: {data?.model||'Checking…'}</p><div className="model-grid">{data?.models?.map((m:any)=><div className="panel" key={m.name}><h3>{m.name}</h3>{m.size>0&&<p>{(m.size/1024**3).toFixed(1)} GB download size</p>}<button disabled={busy||!data.ollama_online} onClick={()=>action('load',m.name)}>Load & use</button></div>)}</div><form className="panel" onSubmit={e=>{e.preventDefault();action('pull',name)}}><label>Download an Ollama model<input required value={name} onChange={e=>setName(e.target.value)} placeholder="llama3.2:1b" pattern="[a-zA-Z0-9_.:/\-]+" maxLength={120}/></label><button disabled={busy||data?.maintenance?.pull?.status==='running'}>Download model</button><p>{data?.maintenance?.pull?.status} {data?.maintenance?.pull?.progress?.status}</p><small>Downloads need internet. Once downloaded, supported local models work offline. Larger models need more RAM.</small></form></section>
}
export function Skills(){
 const [items,setItems]=useState<any[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);
 async function refresh(){setItems(await workApi('/skills'))}
 useEffect(()=>{refresh().catch(e=>setNotice(e.message))},[]);
 async function run(fn:()=>Promise<any>){setBusy(true);try{await fn();await refresh();setNotice('Skills updated. The selected skill applies to your next local answer.')}catch(e:any){setNotice(e.message)}finally{setBusy(false)}}
 return <section><h2>Your skills</h2><p>Select one skill for focused help. Markdown instructions run locally; they cannot execute commands, access files by themselves, or send data to Gemini.</p><button disabled={busy} onClick={()=>input.current?.click()}>Add skill (.md)</button><input ref={input} type="file" hidden accept=".md" onChange={e=>{const file=e.target.files?.[0];if(file)run(async()=>{if(file.size>48000)throw Error('Skill limit: 12,000 characters');await workApi('/skills','POST',{name:file.name,content:await file.text()})});e.target.value=''}}/><p role="status">{notice}</p><div className="skill-grid">{items.map(item=><div className="panel" key={item.id}><h3>{item.name}</h3><details><summary>View instructions</summary><p>{item.content}</p></details><button disabled={busy} aria-pressed={item.enabled} onClick={()=>run(()=>workApi('/skills/'+item.id,'PUT',{enabled:!item.enabled}))}>{item.enabled?'Disable skill':'Use skill'}</button>{!item.builtin&&<button disabled={busy} onClick={()=>run(()=>workApi('/skills/'+item.id,'DELETE'))}>Remove</button>}</div>)}</div></section>
}
export function SavedKnowledge(){
 const [items,setItems]=useState<any[]>([]),[notice,setNotice]=useState('');async function refresh(){setItems(await workApi('/knowledge-cache'))}
 useEffect(()=>{refresh().catch(e=>setNotice(e.message))},[]);
 return <section><h2>Saved web knowledge</h2><p>Dated public references are saved after successful web-assisted answers and can be reused offline. They may become outdated. Learning Lab lessons are managed separately in Learning Lab.</p><p role="status">{notice}</p>{!items.length&&<p>No web knowledge saved yet.</p>}{items.map(x=><div className="panel" key={x.id}><h3>{x.topic}</h3><small>{new Date(x.created*1000).toLocaleString()}</small><details><summary>Answer & references</summary><p>{x.answer}</p>{x.evidence.map((e:any)=><p key={e.url}><a href={e.url} target="_blank" rel="noreferrer">{e.title}</a></p>)}</details><button onClick={async()=>{try{await workApi('/knowledge-cache/'+x.id,'DELETE');await refresh()}catch(e:any){setNotice(e.message)}}}>Forget</button></div>)}</section>
}
export function MemoryOverview(){
 const [data,setData]=useState<any>(null),[notice,setNotice]=useState('');
 async function refresh(){try{setData(await workApi('/memory-overview'))}catch(e:any){setNotice(e.message)}}
 useEffect(()=>{refresh();const t=setInterval(refresh,10000);return()=>clearInterval(t)},[]);
 return <section className="panel"><h2>Everything Nila has saved</h2><p role="status">{notice}</p>{data&&<><div className="memory-counts"><span><b>{data.personal}</b> Personal facts</span><span><b>{data.lessons}</b> Learning Lab lessons</span><span><b>{data.web}</b> Web topics</span><span><b>{data.pending}</b> Awaiting review</span></div><p>{data.total} saved items. Search and Learning Lab knowledge are saved separately from facts about you.</p>{!data.knowledge_enabled&&<p>Knowledge recall is off. Enable “Use saved learning and web knowledge” in Preferences to reuse lessons and web references offline.</p>}{!data.memory_enabled&&<p>Personal memory recall is off in Preferences.</p>}{data.pending>0&&<p>Approve suggested personal facts in Workspace → Memory inbox before Nila uses them.</p>}<details><summary>Recent Learning Lab status</summary>{!data.recent_learning.length&&<p>No Learning Lab sessions yet.</p>}{data.recent_learning.map((x:any,i:number)=><p key={i}><b>{x.topic}</b> · {x.status}{!x.save_knowledge?' · Saving was disabled':''}{x.error?' · '+x.error:''}</p>)}<p>Only accepted reviewer lessons are stored. Stopped, failed, uncertain or correction-only rounds do not become facts automatically.</p></details><p>Inspect saved web evidence under Workspace → Knowledge. Manage reviewed lessons in Learning Lab → Saved knowledge.</p></>}<button type="button" onClick={refresh}>Refresh memory status</button></section>
}
