import {useEffect,useState} from 'react';
import {Cpu} from 'lucide-react';
import {workApi} from './Workspace';
export function ModelSelector({compact=false,disabled=false,onError}:{compact?:boolean;disabled?:boolean;onError:(message:string)=>void}){
 const [data,setData]=useState<any>(null),[installed,setInstalled]=useState<any[]>([]),[switching,setSwitching]=useState(false);
 async function refresh(){const [d,s]=await Promise.all([workApi('/models/profiles'),workApi('/status')]);setData(d);setInstalled(s.models||[])}
 useEffect(()=>{const reload=()=>{refresh().catch(e=>onError(e.message))};reload();window.addEventListener('nila-settings-changed',reload);window.addEventListener('focus',reload);const t=setInterval(reload,15000);return()=>{window.removeEventListener('nila-settings-changed',reload);window.removeEventListener('focus',reload);clearInterval(t)}},[]);
 const value=data?.mode==='custom'?data.model:data?.mode||'';
 async function choose(value:string){setSwitching(true);try{setData(await workApi('/models/select','POST',{value}));window.dispatchEvent(new Event('nila-settings-changed'))}catch(e:any){onError(e.message)}finally{setSwitching(false)}}
 return <label className={compact?'icon-select':'profile-select'} title={'Model: '+(data?.label||'Loading')}><Cpu size={17}/>{!compact&&<span>{switching?'Switching…':data?.label||'Model'}</span>}<select aria-label={compact?'Local model':'Active model profile'} disabled={disabled||switching||!data} value={value} onChange={e=>choose(e.target.value)}>{!data&&<option value="">Loading…</option>}{data?.profiles.map((p:any)=><option key={p.id} value={p.id}>{({fast:'⚡',medium:'⚖️',current:'🧠'} as Record<string,string>)[p.id]} {p.label} — {p.model}{installed.some(m=>m.name===p.model)?'':' — install first'}</option>)}{data?.mode==='custom'&&!installed.some(m=>m.name===data.model)&&<option value={data.model}>Custom: {data.model}</option>}{installed.filter(m=>!data?.profiles.some((p:any)=>p.model===m.name)).map(m=><option key={m.name} value={m.name}>Custom: {m.name}</option>)}</select></label>
}
export function ProfileCards({installed,busy,load,download}:{installed:any[];busy:boolean;load:(value:string)=>void;download:(value:string)=>void}){
 const [data,setData]=useState<any>(null),[draft,setDraft]=useState<Record<string,string>>({}),[notice,setNotice]=useState('');
 useEffect(()=>{workApi('/models/profiles').then(d=>{setData(d);setDraft(Object.fromEntries(d.profiles.map((p:any)=>[p.id,p.model])))}).catch(e=>setNotice(e.message))},[]);
 return <><div className="model-grid">{data?.profiles.map((p:any)=><div className="panel" key={p.id}><h3>{p.label}</h3><p>{p.purpose}</p><small>{p.model}</small><p><button disabled={busy} onClick={()=>installed.some(m=>m.name===p.model)?load(p.model):download(p.model)}>{installed.some(m=>m.name===p.model)?'Load & use '+p.label:'Download '+p.label}</button></p></div>)}</div><details className="panel"><summary>Configure profile model names</summary><form onSubmit={async e=>{e.preventDefault();try{const d=await workApi('/models/profiles','PUT',draft);setData(d);window.dispatchEvent(new Event('nila-settings-changed'));setNotice('Profile mapping saved. Download any missing model before chatting.')}catch(e:any){setNotice(e.message)}}}>{data?.profiles.map((p:any)=><label key={p.id}>{p.label}<input required value={draft[p.id]||''} pattern="[a-zA-Z0-9_.:/\-]+" maxLength={120} onChange={e=>setDraft({...draft,[p.id]:e.target.value})}/></label>)}<button disabled={busy}>Save profiles</button><p role="status">{notice}</p></form></details></>
}
