import {useEffect,useRef,useState} from 'react';
import {workApi} from './Workspace';
export function RuntimePanel(){
 const previousRunning=useRef(false);
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[profile,setProfile]=useState('fast');
 useEffect(()=>{let active=true;const refresh=()=>workApi('/runtime').then(d=>{if(active){setData(d);if(previousRunning.current&&!d.job.running)window.dispatchEvent(new Event('nila-settings-changed'));previousRunning.current=d.job.running}}).catch(e=>{if(active)setError(e.message)});refresh();const timer=setInterval(refresh,1500);return()=>{active=false;clearInterval(timer)}},[]);
 async function setup(component:string){try{setError('');await workApi('/runtime/setup','POST',{component,profile});setData(await workApi('/runtime'));window.dispatchEvent(new Event('nila-settings-changed'))}catch(e:any){setError(e.message)}}
 return <div className="panel"><h2>Engine & downloads</h2><p>Components download once and are reused. Setup continues while you navigate. Local generation queues to protect available RAM.</p>{error&&<p role="alert">{error}</p>}{data&&<><p>Active engine: <strong>{data.runtime.engine}</strong> · {data.runtime.model}</p><label>llama.cpp model<select value={profile} onChange={e=>setProfile(e.target.value)}><option value="fast">Fast · Qwen3 0.6B · smaller download</option><option value="medium">Medium · Qwen3 1.7B</option><option value="smart">Smart · Qwen3 4B · more RAM required</option><option value="vision">Vision · SmolVLM 500M</option></select></label><button disabled={data.job.running} onClick={()=>setup('ollama')}>Use Ollama</button><button disabled={data.job.running} onClick={()=>setup('llama.cpp')}>Install / use llama.cpp</button><h3>Offline speech</h3><p>Whisper base multilingual recognition and Piper English voice. Downloads Python tools and model files; microphone access requires your click.</p><button disabled={data.job.running||data.speech.installed} onClick={()=>setup('speech')}>{data.speech.installed?'Speech pack ready':'Install speech pack'}</button><h3>Image understanding</h3><p>Download and select a vision model for the active engine. Text PDFs, TXT and Markdown use your existing chat model; scanned PDFs require OCR.</p><button disabled={data.job.running} onClick={()=>setup('vision')}>Install / use vision model</button><p role="status">{data.job.message}</p>{data.job.error&&<p role="alert">{data.job.error}</p>}</>}</div>
}
