import {Models,Skills,SavedKnowledge} from './LocalTools';
import {Telegram} from './Telegram';
import {SystemPanel} from './ExtensionPanels';
import React,{useEffect,useState} from 'react';
import {Check,RefreshCw,ShieldCheck,FileText,Brain,FolderOpen,Archive,Sun,Settings2,ThumbsUp} from 'lucide-react';
export async function workApi(path:string,method='GET',body?:unknown):Promise<any>{
 const r=await fetch('/api'+path,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});
 const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'Check the entered values');return d;
}
async function encoded(file:File){
 if(file.size>20*1024*1024)throw Error('Maximum file size: 20 MB');
 return await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result).split(',')[1]);r.onerror=reject;r.readAsDataURL(file)});
}
export function Workspace({openChat,initial='Today'}:{openChat:(id:string)=>void;initial?:string}){
 const [tab,setTab]=useState(initial),[data,setData]=useState<any>(null),[setup,setSetup]=useState<any>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [name,setName]=useState(''),[instructions,setInstructions]=useState(''),[project,setProject]=useState(''),[editing,setEditing]=useState(''),[password,setPassword]=useState(''),[backup,setBackup]=useState<File|null>(null),[preview,setPreview]=useState<any>(null),[jobs,setJobs]=useState<any[]>([]);
 const [confirmation,setConfirmation]=useState<{message:string;resolve:(v:boolean)=>void}|null>(null);
 const ask=(message:string)=>new Promise<boolean>(resolve=>setConfirmation({message,resolve}));
 const fail=(e:any)=>setError(e.message||String(e));
 const refresh=async()=>{setData(await workApi('/workspace'));};
 useEffect(()=>{refresh().catch(fail)},[]);
 useEffect(()=>{if(tab==='Setup')workApi('/setup').then(setSetup).catch(fail)},[tab]);
 async function run(fn:()=>Promise<any>,message='Saved'){setBusy(true);setError('');try{await fn();setNotice(message);await refresh()}catch(e){fail(e)}finally{setBusy(false)}}
 async function start(pid?:string,doc?:string){await run(async()=>{const c=await workApi('/chats','POST',{project_id:pid||null});if(doc)await workApi(`/chats/${c.id}/documents`,'PUT',{ids:[doc]});openChat(c.id)},'Conversation ready')}
 async function exportBackup(){setBusy(true);setError('');try{const r=await fetch('/api/backup/export',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password})});if(!r.ok)throw Error((await r.json()).detail);const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='nila-backup.nila';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setPassword('');setNotice('Encrypted backup downloaded. Keep its password safe.')}catch(e){fail(e)}finally{setBusy(false)}}
 return <div className="page-scroll"><section className="settings-page workspace"><div className="eyebrow">YOUR LOCAL WORKSPACE</div><h1>More personal. More in control.</h1><p>Documents, memories and preferences stay with your local assistant. Gemini cannot access this workspace.</p>
 <div className="workspace-tabs">{[['Today',Sun],['Models',Settings2],['Skills',FileText],['Knowledge',Brain],['Setup',Settings2],['Memory inbox',Brain],['Projects',FolderOpen],['Documents',FileText],['Backup',Archive],['Telegram',ShieldCheck],['System',Settings2],['Versions',RefreshCw]].map(([label,Icon]:any)=><button key={label} className={tab===label?'selected':''} onClick={()=>setTab(label)}><Icon size={15}/>{label}</button>)}</div>
 {confirmation&&<div className="section-confirm" role="region" aria-label="Confirm action"><p>{confirmation.message}</p><button onClick={()=>{confirmation.resolve(true);setConfirmation(null)}}>Confirm</button><button onClick={()=>{confirmation.resolve(false);setConfirmation(null)}}>Cancel</button></div>}
 {error&&<div className="error-banner" role="alert">{error}</div>}{notice&&<p role="status">{notice}</p>}
 {!data?<p>Loading workspace…</p>:<>
 {tab==='Today'&&<><div className="panel"><h2>Your workspace today</h2><p>{data.brief.conversations} conversations · {data.brief.projects} projects · {data.brief.documents} documents</p><button onClick={()=>setTab('Memory inbox')}>{data.brief.pending_memories} memories awaiting review</button></div><div className="panel"><h2>Mini Nila</h2><p>Ctrl + Shift + Space inside Nila opens a compact chat window. The shortcut works while Nila has keyboard focus.</p><a href="/?mini=1" target="_blank" rel="noreferrer">Open compact view</a></div></>}
 {tab==='Setup'&&<div className="panel"><h2>Setup wizard</h2><p>Check your device, connect Ollama, choose a model, then finish setup.</p>{setup?<><p><ShieldCheck size={16}/> Encrypted local storage · {setup.key_protection}</p><p>RAM: {setup.ram_gb} GB total · {setup.available_ram_gb} GB available</p><p>Ollama: {setup.ollama_online?'Connected':'Not connected — open Ollama or run ollama serve'}</p><p>Selected model: {setup.model} · {setup.model_ready?'Ready':'Not installed'}</p><p>RAM estimates include a rough overhead margin; context length and other apps affect actual usage.</p>{setup.suggestions.map((m:any)=><div className="workspace-row" key={m.name}><span><strong>{m.name}</strong><small>Estimated {m.estimated_ram_gb} GB · {m.fits_available_ram?'Suggested for available RAM':'May exceed available RAM'}</small></span><button disabled={busy} onClick={()=>run(async()=>{await workApi('/settings','PUT',{...await workApi('/settings'),model:m.name});setSetup(await workApi('/setup'));window.dispatchEvent(new Event('nila-settings-changed'))},'Model selected')}>Use model</button></div>)}<button disabled={busy||!setup.ollama_online} onClick={()=>run(()=>workApi('/models/pull','POST',{model:setup.model}),'Model download started. See System for progress, then recheck.')}>Download selected model</button><button disabled={busy} onClick={()=>run(async()=>setSetup(await workApi('/setup')),'Checks refreshed')}>Recheck requirements</button><button className="primary" disabled={busy||!setup.model_ready} onClick={()=>run(async()=>{await workApi('/setup/complete','POST');window.dispatchEvent(new Event('nila-settings-changed'));setTab('Today')},'Setup complete. Open a conversation to start.')}>Finish setup</button><p>Windows prerequisites are installed by the one-command installer. This wizard does not change system settings.</p></>:<p>Checking requirements…</p>}</div>}
 {tab==='Memory inbox'&&<div className="panel"><h2>Review before remembering</h2><label className="check"><input type="checkbox" checked={data.memory_review} onChange={e=>run(()=>workApi('/memory-review','POST',{enabled:e.target.checked}))}/>Review automatically suggested memories before use</label><p>Sensitive statements are excluded from automatic extraction. Suggestions are encrypted and are not used until approved.</p>{!data.inbox.length&&<p>No suggestions waiting.</p>}{data.inbox.map((m:any)=><MemoryCard key={m.id} item={m} busy={busy} decide={(approve:boolean,content:string)=>run(()=>workApi('/memory-inbox/'+m.id,'POST',{approve,content}),approve?'Memory approved':'Suggestion rejected')}/>)}</div>}
 {tab==='Projects'&&<><form className="panel" onSubmit={e=>{e.preventDefault();run(async()=>{await workApi('/projects'+(editing?'/'+editing:''),editing?'PUT':'POST',{name,instructions});setName('');setInstructions('');setEditing('')},'Project saved')}}><h2>{editing?'Edit project':'New project'}</h2><label>Project name<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)}/></label><label>Instructions<textarea maxLength={3000} value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="How should Nila help with this project?"/></label><button className="primary" disabled={busy}>Save project</button>{editing&&<button type="button" onClick={()=>{setEditing('');setName('');setInstructions('')}}>Cancel</button>}</form><div className="panel">{data.projects.map((p:any)=><div className="workspace-row" key={p.id}><span><strong>{p.name}</strong><small>{p.instructions}</small></span><div><button disabled={busy} onClick={()=>start(p.id)}>Start chat</button><button onClick={()=>{setEditing(p.id);setName(p.name);setInstructions(p.instructions)}}>Edit</button><button disabled={busy} onClick={async()=>{if(await ask('Delete this project and its documents? Chats remain, without the project.'))run(()=>workApi('/projects/'+p.id,'DELETE'))}}>Delete</button></div></div>)}</div></>}
 {tab==='Documents'&&<div className="panel"><h2>Chat with local documents</h2><p>PDF, UTF-8 TXT or Markdown · up to 5 MB / 100 PDF pages. Scanned PDFs need OCR first. Only extracted text is stored, encrypted. Gemini never receives it.</p><label>Project (optional)<select value={project} onChange={e=>setProject(e.target.value)}><option value="">No project — attach to individual chats</option>{data.projects.map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Import document<input type="file" accept=".pdf,.txt,.md" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)run(async()=>{if(f.size>5*1024*1024)throw Error('Document limit is 5 MB');await workApi('/documents','POST',{name:f.name,data:await encoded(f),project_id:project||null})},'Document ready');e.target.value=''}}/></label>{data.documents.map((d:any)=><div className="workspace-row" key={d.id}><span>{d.name}</span><div><button disabled={busy} onClick={()=>start(d.project_id,d.id)}>Ask about file</button><button disabled={busy} onClick={async()=>{if(await ask('Delete this document?'))run(()=>workApi('/documents/'+d.id,'DELETE'))}}>Delete</button></div></div>)}</div>}
 {tab==='Backup'&&<div className="panel"><h2>Encrypted backup & restore</h2><p>Export your saved workspace with a password. API keys and temporary chats are excluded. Restore replaces saved data and disables Telegram. Keep a current backup first.</p><label>Backup password<input type="password" autoComplete="new-password" minLength={12} maxLength={256} value={password} onChange={e=>{setPassword(e.target.value);setPreview(null)}} placeholder="At least 12 characters"/></label><button disabled={busy||password.length<12} onClick={exportBackup}>Download encrypted backup</button><label>Restore file<input type="file" accept=".nila" onChange={e=>{setBackup(e.target.files?.[0]||null);setPreview(null)}}/></label><button disabled={busy||!backup||password.length<12} onClick={()=>run(async()=>setPreview(await workApi('/backup/restore','POST',{password,data:await encoded(backup!)})),'Backup checked')}>Preview restore</button>{preview&&<><p>{preview.notice}</p><pre>{JSON.stringify(preview.counts,null,2)}</pre><button className="primary" disabled={busy} onClick={async()=>{if(await ask('Replace saved workspace data with this backup? This cannot be undone without your current backup.'))run(async()=>{await workApi('/backup/restore','POST',{password,data:await encoded(backup!),apply:true});setPreview(null);setPassword('');setBackup(null)},'Restored. Restart Nila before reconnecting Telegram.')}}>Replace workspace & restore</button></>}</div>}
 {tab==='Knowledge'&&<SavedKnowledge/>}{tab==='Models'&&<Models/>}{tab==='Skills'&&<Skills/>}{tab==='Telegram'&&<Telegram/>}
 {tab==='System'&&<SystemPanel/>}
 {tab==='Versions'&&<><div className="panel"><h2>Update rollback</h2><p>Managed Windows installs can select the previous installed binary. Your data remains. Back up first: old versions may not understand new data. Restart Nila and its worker afterward.</p><button disabled={busy} onClick={async()=>{if(await ask('Select the previous installed version and pause automatic updates?'))run(async()=>{const r=await workApi('/update/rollback','POST');setNotice(r.message)},'Previous version selected; restart Nila. Automatic updates paused.')}}>Roll back installed version</button></div></>}
 </>}{busy&&<p role="status" className="working-indicator">Working locally…</p>}</section></div>
}
function MemoryCard({item,busy,decide}:any){const [text,setText]=useState(item.content);return <div className="workspace-card"><textarea aria-label="Suggested memory" value={text} maxLength={2000} onChange={e=>setText(e.target.value)}/><button disabled={busy||!text.trim()} onClick={()=>decide(true,text)}>Approve memory</button><button disabled={busy} onClick={()=>decide(false,'')}>Reject</button></div>}
function FeedbackCard({item,busy,save,remove}:any){const [reason,setReason]=useState(item.reason);return <div className="workspace-card"><small>{item.rating===1?'Helpful':'Unhelpful'} · {item.content.slice(0,180)}</small><textarea aria-label="Edit feedback guidance" maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/><button disabled={busy} onClick={()=>save(reason)}>Save guidance</button><button disabled={busy} onClick={remove}>Remove feedback</button></div>}
export function ChatWorkspace({cid,temporary,busy}:{cid:string;temporary?:boolean;busy:boolean}){
 const [data,setData]=useState<any>(null),[selected,setSelected]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{if(!temporary)Promise.all([workApi('/workspace'),workApi(`/chats/${cid}/workspace`)]).then(([d,s])=>{setData(d);setSelected(s)}).catch(e=>setError(e.message))},[cid,temporary]);
 if(temporary)return <p className="temporary-note">Temporary chat · held in memory until closed or server exits · no persistent memories, attachments or feedback</p>;
 if(!data||!selected)return null;
 async function update(path:string,body:any){try{await workApi(`/chats/${cid}/`+path,'PUT',body);setSelected(await workApi(`/chats/${cid}/workspace`));setError('')}catch(e:any){setError(e.message)}}
 return <details className="chat-workspace"><summary>Project & documents {selected.parent_id?'· branched conversation':''}</summary>{error&&<p role="alert">{error}</p>}<label>Chat project<select value={selected.project_id||''} disabled={busy} onChange={e=>update('project',{project_id:e.target.value||null})}><option value="">No project</option>{data.projects.map((p:any)=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>{data.documents.map((d:any)=><label className="check" key={d.id}><input type="checkbox" disabled={busy} checked={selected.document_ids.includes(d.id)} onChange={e=>update('documents',{ids:e.target.checked?[...selected.document_ids,d.id]:selected.document_ids.filter((id:string)=>id!==d.id)})}/>{d.name}</label>)}<small>Project files are included automatically. Other files must be attached here.</small></details>
}
